name: lazy_engineer
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  dio: ^5.4.1
  equatable: ^2.0.5
  file_picker: ^6.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.7.0
  lottie: ^3.1.0
  open_app_file: ^4.0.1
  path_provider: ^2.0.11
  pdf_image_renderer: ^0.7.0
  pretty_dio_logger: ^1.1.1
  retrofit: ^4.1.0
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  hive_generator: null
  json_serializable: ^6.4.1
  lint: ^2.0.1
  retrofit_generator: ^8.1.0
  url_strategy: ^0.2.0

flutter_icons:
  image_path: "assets/icons/logo.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/animations/